### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by dtinth** [Cleverse/thailand-party-list-calculator#2]
Thanks for creating this project! Helps me understand the election rules more easily :P

I found that this module isn’t on npm yet:
https://www.npmjs.com/package/thailand-party-list-calculator

Can you publish the package to `npm` so that it can be easily installed?

**Comment by PanJ** [comment]
Published npm package at https://www.npmjs.com/package/thailand-party-list-calculator

Thanks for the issue!
