### ISSUE TITLE
Anyone understand (6): 'ให้นําค่าเฉลี่ยคะแนนของแต่ละพรรคการเมืองต่อจํานวนสมาชิกสภาผู้แทนราษฎรที่พึงมีหนึ่งคนมาพิจารณา '

### ISSUE THREAD

**Issue by ghost** [Cleverse/thailand-party-list-calculator#9]
Anyone understand (6): 'ให้นําค่าเฉลี่ยคะแนนของแต่ละพรรคการเมืองต่อจํานวนสมาชิกสภาผู้แทนราษฎรที่พึงมีหนึ่งคนมาพิจารณา ' .. is that average value the same for all parties????

p.repCeiling = p.voteCount / score4Rep

Now (6) suggests to do this ... p.voteCount/p.repCeiling ... that is score4Rep, right? And that should be the same for all parties, right? Do I miss something?

**Comment by Woracheth** [comment]
This was disscussed in #3 

From @PanJ interpretation, he suggested that p.repCeiling is a rounded separately for each particular party (as stated at the end of the first paragraph of section 128).
`p.repCeiling = rounddown(p.voteCount / score4Rep, 4)`
Therefore, the division result would not translate back to the same score4Rep
`p.voteCount / p.repCeiling != score4Rep`
then little difference from the division result could distinguish an outstanding the party.

Another version from his statement, as I understand,
`(ค่าเฉลี่ย = ((คะแนนของพรรคการเมือง)ต่อ(หนึ่งคน(จํานวนสมาชิกสภาผู้แทนราษฎรที่พึงมี))))`
means
`(average = ((p.voteCount) / (floor(p.repCeiling))))`

This latter logic is implemented in compareParty()
```
  const aRepCeiling = a.getRepCeilingInt().toNumber()
  const bRepCeiling = b.getRepCeilingInt().toNumber()
  const aTempValue = a.voteCount / aRepCeiling
  const bTempValue = b.voteCount / bRepCeiling
```
where getRepCeilingInt() yields a floored repCeiling value, i.e. ceiling of any party is stomped by the regulation

**Comment by ghost** [comment]
Thank you for the clarification. This is sufficient. I am happy. Hence, i will close this issue.
